custom check 1 (#33)
* custom check 1

* custom check remove

* custom check 2

* custom check 3

* remove comment

* add warning

* remove Token

* label check

* label 2

* label 2-1

* label 2-2

* label 2-3

* label 2-4

* label 2-5

* label 2-6

* changes yaml

Co-authored-by: oleh rybnikov <valor-team@valor-teams-Mac-mini.local>

diff --git a/.github/workflows/on-pr-or-push.yml b/.github/workflows/on-pr-or-push.yml
--- a/.github/workflows/on-pr-or-push.yml
+++ b/.github/workflows/on-pr-or-push.yml
@@ -2,6 +2,7 @@ name: ci
 
 on:
   pull_request:
+    types: [ labeled, opened, synchronize, reopened ]
   push:
     branches:
       - main
@@ -35,49 +36,50 @@ jobs:
         id: storybooks-related-lib-changed
         run: echo "::set-output name=storybooks-related-lib-changed::$(node scripts/ci-is-affected.mjs --base=${{ env.BASE_REF}} --head=HEAD --target=storybook-mark)"
 
-#  test:
-#    needs: install
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          fetch-depth: 0 # Required to retrieve git history
-#
-#      - uses: actions/cache@v3
-#        with:
-#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
-#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
-#
-#      - name: test
-#        run: npm test
-#
-#  build:
-#    needs: install
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v3
-#
-#      - uses: actions/cache@v3
-#        with:
-#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
-#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
-#
-#      - name: build
-#        run: npm run build
+  test:
+    needs: install
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Required to retrieve git history
 
-#  check-storybook:
-#    needs: install
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v3
-#
-#      - uses: actions/cache@v3
-#        with:
-#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
-#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
-#
-#      - name: check-storybook
-#        run: npm run build-storybook
+      - uses: actions/cache@v3
+        with:
+          path: ${{ env.CACHE_NODE_MODULES_PATH }}
+          key: node_modules-${{ hashFiles('**/package-lock.json') }}
+
+      - name: test
+        run: npm test
+
+  build:
+    needs: install
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/cache@v3
+        with:
+          path: ${{ env.CACHE_NODE_MODULES_PATH }}
+          key: node_modules-${{ hashFiles('**/package-lock.json') }}
+
+      - name: build
+        run: npm run build
+
+  check-storybook:
+    needs: install
+    if: ${{ needs.install.outputs.storybooks-related-lib-changed == 'true'}}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/cache@v3
+        with:
+          path: ${{ env.CACHE_NODE_MODULES_PATH }}
+          key: node_modules-${{ hashFiles('**/package-lock.json') }}
+
+      - name: check-storybook
+        run: npm run build-storybook
 #      - name: Cache storybook
 #        uses: actions/upload-artifact@v3
 #        with:
@@ -85,9 +87,25 @@ jobs:
 #          path: dist/storybook/ui
 #          retention-days: 1
 
+  check-chromatic-label:
+    needs: check-storybook
+    if: ${{ !contains(github.event.pull_request.labels.*.name, 'chromatic')}}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/github-script@v6
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: '⚠️ This PR potentially has changes covered by storybook. Set a `chromatic` label to verify them'
+            })
+
+
   check-chromatic-pr:
-    needs: install
-    if: ${{ needs.install.outputs.storybooks-related-lib-changed == 'true' && github.ref != 'refs/heads/main'}}
+    needs: check-storybook
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'chromatic') && github.ref != 'refs/heads/main'}}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -104,10 +122,42 @@ jobs:
 
       - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes  --storybook-build-dir=dist/storybook/ui
 
+#  comment:
+#    if: ${{ !contains(github.event.pull_request.labels.*.name, 'chromatic') }}
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/github-script@v6
+#        with:
+#          script: |
+#            github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: '⚠️ Thanks for reporting! 1'
+#            })
+
+#  check-1:
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v3
+#    - run: echo ${{github.event.pull_request.labels}}
+#    - name: Try to fail
+#      run: exit 1
+#
+#  check-2:
+#    needs: install
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Try to OK
+#        run: exit 0
+#          - name: Print message if we don't fail
+#            run: echo Should not get here
+
 
   apply-chromatic:
     needs: install
-    if: ${{ needs.install.outputs.storybooks-related-lib-changed == 'true' && github.ref == 'refs/heads/main'}}
+    if: ${{ github.ref == 'refs/heads/main' && contains(github.event.pull_request.labels.*.name, 'chromatic')}}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
